apiVersion: v1
kind: Secret
metadata:
  name: repo-{{ .Values.django_app_name | default "django-app" }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {{ .Values.gitops_repo_url | quote }}
  type: git
