apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.repository.name }}
  namespace: {{ .Values.application.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: {{ .Values.repository.type }}
  url: {{ .Values.repository.url }}
