replicaCount: 2

image:
  repository: 082228066503.dkr.ecr.us-west-2.amazonaws.com/lesson-7-ecr
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  DEBUG: "False"
  SECRET_KEY: "django-insecure-change-this-in-production-xyz123"
  ALLOWED_HOSTS: "*"

  # DB switch (SQLite default for demo)
  DB_ENGINE: "django.db.backends.sqlite3"
  DB_NAME: "/tmp/db.sqlite3"
  DB_HOST: ""
  DB_PORT: ""
  DB_USER: ""
  DB_PASSWORD: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  liveness:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 3

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
